#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务端口号
server:
  port: 8888
#应用名称
#git远程仓库的配置信息 地址 账号 秘钥 本地保存配置文件的路径
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:gb-heima/config-rep.git
          username:
          password:
          basedir: /Users/Administrator.PC-20180929LWLP/Desktop/springcloud-practical-column/sc-f-chapter6/config/basedir

